COLUMNS:
  fixed acidity: float64
  volatile acidity: float64
  citric acid: float64
  residual sugar: float64  # ✅ Removed extra space after "sugar"
  chlorides: float64
  free sulfur dioxide: float64
  total sulfur dioxide: float64  # ✅ Removed extra space
  density: float64
  pH: float64  # ✅ Removed extra space
  sulphates: float64  # ✅ Removed extra space
  alcohol: float64
  quality: int64              

TARGET_COLUMN:
  name: quality  # ✅ Correct indentation
  TARGET_COLUMN: "price"

